<?php

namespace mauriziocingolani\yii2fmwkplaces\migrations;

class NazioneISO3166 extends \mauriziocingolani\yii2fmwkphp\Migration {

    public function create() {
        $this->createTable('places_nazioni_iso3166', [
            'NazioneID' => self::Pk(),
            'NazioneIt' => self::typeVarchar(255, true),
            'NazioneEn' => self::typeVarchar(255, true),
            'NazioneCodice' => self::typeChar(3, true),
            self::Pk('NazioneID'),
                ], self::TableOptionsLatin());
        $this->createIndex('unique_placesnazioni_nazioneit', 'places_nazioni_iso3166', 'NazioneIt', true);
        $this->createIndex('unique_placesnazioni_nazioneen', 'places_nazioni_iso3166', 'NazioneEn', true);
        $this->createIndex('unique_placesnazioni_nazionecodice', 'places_nazioni_iso3166', 'NazioneCodice', true);
    }

    public function data() {
        $this->batchInsert('places_nazioni_iso3166', ['NazioneID', 'NazioneIy', 'NazioneEn', 'NazioneCode'], [
            [1, 'Afghanistan', ' Afghanistan', 'AFG'],
            [2, 'Albania', ' Albania', 'ALB'],
            [7, 'Antartide', ' Antarctica', 'ATA'],
            [3, 'Algeria', ' Algeria', 'DZA'],
            [198, 'Samoa Americane', ' American Samoa', 'ASM'],
            [4, 'Andorra', ' Andorra', 'AND'],
            [5, 'Angola', ' Angola', 'AGO'],
            [8, 'Antigua e Barbuda', ' Antigua and Barbuda', 'ATG'],
            [15, 'Azerbaigian', ' Azerbaijan', 'AZE'],
            [10, 'Argentina', ' Argentina', 'ARG'],
            [13, 'Australia', ' Australia', 'AUS'],
            [14, 'Austria', ' Austria', 'AUT'],
            [16, 'Bahamas', ' Bahamas', 'BHS'],
            [17, 'Bahrein', ' Bahrain', 'BHR'],
            [18, 'Bangladesh', ' Bangladesh', 'BGD'],
            [11, 'Armenia', ' Armenia', 'ARM'],
            [19, 'Barbados', ' Barbados', 'BRB'],
            [20, 'Belgio', ' Belgium', 'BEL'],
            [23, 'Bermuda', ' Bermuda', 'BMU'],
            [24, 'Bhutan', ' Bhutan', 'BTN'],
            [27, 'Bolivia', ' Bolivia', 'BOL'],
            [28, 'Bosnia ed Erzegovina', ' Bosnia and Herzegovina', 'BIH'],
            [29, 'Botswana', ' Botswana', 'BWA'],
            [98, 'Isola Bouvet', ' Bouvet Island', 'BVT'],
            [30, 'Brasile', ' Brazil', 'BRA'],
            [21, 'Belize', ' Belize', 'BLZ'],
            [226, 'Territorio britannico dell\'Oceano Indiano', ' British Indian Ocean Territory', 'IOT'],
            [114, 'Isole Salomone', ' Solomon Islands', 'SLB'],
            [115, 'Isole Vergini britanniche', ' Virgin Islands (British)', 'VGB'],
            [31, 'Brunei', ' Brunei Darussalam', 'BRN'],
            [32, 'Bulgaria', ' Bulgaria', 'BGR'],
            [26, 'Birmania', ' Myanmar', 'MMR'],
            [34, 'Burundi', ' Burundi', 'BDI'],
            [25, 'Bielorussia', ' Belarus', 'BLR'],
            [35, 'Cambogia', ' Cambodia', 'KHM'],
            [36, 'Camerun', ' Cameroon', 'CMR'],
            [37, 'Canada', ' Canada', 'CAN'],
            [38, 'Capo Verde', ' Cabo Verde', 'CPV'],
            [104, 'Isole Cayman', ' Cayman Islands', 'CYM'],
            [182, 'Rep. Centrafricana', ' Central African Republic', 'CAF'],
            [212, 'Sri Lanka', ' Sri Lanka', 'LKA'],
            [39, 'Ciad', ' Chad', 'TCD'],
            [40, 'Cile', ' Chile', 'CHL'],
            [41, 'Cina', ' China', 'CHN'],
            [222, 'Taiwan', ' Taiwan', 'TWN'],
            [100, 'Isola di Natale', ' Christmas Island', 'CXR'],
            [105, 'Isole Cocos (Keeling)', ' Cocos (Keeling) Islands', 'CCK'],
            [44, 'Colombia', ' Colombia', 'COL'],
            [45, 'Comore', ' Comoros', 'COM'],
            [146, 'Mayotte', ' Mayotte', 'MYT'],
            [183, 'Rep. del Congo', ' Congo', 'COG'],
            [180, 'Rep. Democratica  del Congo', ' Congo, Democratic Republic of the', 'COD'],
            [118, 'Isole Cook', ' Cook Islands', 'COK'],
            [49, 'Costa Rica', ' Costa Rica', 'CRI'],
            [50, 'Croazia', ' Croatia', 'HRV'],
            [51, 'Cuba', ' Cuba', 'CUB'],
            [42, 'Cipro', ' Cyprus', 'CYP'],
            [181, 'Rep. Ceca', ' Czechia', 'CZE'],
            [22, 'Benin', ' Benin', 'BEN'],
            [53, 'Danimarca', ' Denmark', 'DNK'],
            [54, 'Dominica', ' Dominica', 'DMA'],
            [184, 'Rep. Dominicana', ' Dominican Republic', 'DOM'],
            [55, 'Ecuador', ' Ecuador', 'ECU'],
            [57, 'El Salvador', ' El Salvador', 'SLV'],
            [86, 'Guinea Equatoriale', ' Equatorial Guinea', 'GNQ'],
            [61, 'Etiopia', ' Ethiopia', 'ETH'],
            [59, 'Eritrea', ' Eritrea', 'ERI'],
            [60, 'Estonia', ' Estonia', 'EST'],
            [107, 'Fær Øer', ' Faroe Islands', 'FRO'],
            [108, 'Isole Falkland', ' Falkland Islands (Malvinas)', 'FLK'],
            [69, 'Georgia del Sud e Isole Sandwich Australi', ' South Georgia and the South Sandwich Islands', 'SGS'],
            [62, 'Figi', ' Fiji', 'FJI'],
            [64, 'Finlandia', ' Finland', 'FIN'],
            [102, 'Isole Åland', ' Åland Islands', 'ALA'],
            [65, 'Francia', ' France', 'FRA'],
            [88, 'Guyana francese', ' French Guiana', 'GUF'],
            [173, 'Polinesia francese', ' French Polynesia', 'PYF'],
            [225, 'Terre australi e antartiche francesi', ' French Southern Territories', 'ATF'],
            [75, 'Gibuti', ' Djibouti', 'DJI'],
            [66, 'Gabon', ' Gabon', 'GAB'],
            [68, 'Georgia', ' Georgia', 'GEO'],
            [67, 'Gambia', ' Gambia', 'GMB'],
            [168, 'Palestina', ' Palestine, State of', 'PSE'],
            [70, 'Germania', ' Germany', 'DEU'],
            [71, 'Ghana', ' Ghana', 'GHA'],
            [74, 'Gibilterra', ' Gibraltar', 'GIB'],
            [123, 'Kiribati', ' Kiribati', 'KIR'],
            [77, 'Grecia', ' Greece', 'GRC'],
            [79, 'Groenlandia', ' Greenland', 'GRL'],
            [78, 'Grenada', ' Grenada', 'GRD'],
            [80, 'Guadalupa', ' Guadeloupe', 'GLP'],
            [81, 'Guam', ' Guam', 'GUM'],
            [82, 'Guatemala', ' Guatemala', 'GTM'],
            [84, 'Guinea', ' Guinea', 'GIN'],
            [87, 'Guyana', ' Guyana', 'GUY'],
            [89, 'Haiti', ' Haiti', 'HTI'],
            [109, 'Isole Heard e McDonald', ' Heard Island and McDonald Islands', 'HMD'],
            [43, 'Città del Vaticano', ' Holy See', 'VAT'],
            [90, 'Honduras', ' Honduras', 'HND'],
            [91, 'Hong Kong', ' Hong Kong', 'HKG'],
            [240, 'Ungheria', ' Hungary', 'HUN'],
            [97, 'Islanda', ' Iceland', 'ISL'],
            [92, 'India', ' India', 'IND'],
            [93, 'Indonesia', ' Indonesia', 'IDN'],
            [94, 'Iran', ' Iran (Islamic Republic of)', 'IRN'],
            [95, 'Iraq', ' Iraq', 'IRQ'],
            [96, 'Irlanda', ' Ireland', 'IRL'],
            [117, 'Israele', ' Israel', 'ISR'],
            [106, 'Italia', ' Italy', 'ITA'],
            [48, 'Costa d\Avorio', ' Côte d\'Ivoire', 'CIV'],
            [72, 'Giamaica', ' Jamaica', 'JAM'],
            [73, 'Giappone', ' Japan', 'JPN'],
            [120, 'Kazakistan', ' Kazakhstan', 'KAZ'],
            [76, 'Giordania', ' Jordan', 'JOR'],
            [121, 'Kenya', ' Kenya', 'KEN'],
            [46, 'Corea del Nord', ' Korea (Democratic People\'s Republic of)', 'PRK'],
            [47, 'Corea del Sud', ' Korea, Republic of', 'KOR'],
            [124, 'Kuwait', ' Kuwait', 'KWT'],
            [122, 'Kirghizistan', ' Kyrgyzstan', 'KGZ'],
            [125, 'Laos', ' Lao People\'s Democratic Republic', 'LAO'],
            [128, 'Libano', ' Lebanon', 'LBN'],
            [126, 'Lesotho', ' Lesotho', 'LSO'],
            [127, 'Lettonia', ' Latvia', 'LVA'],
            [129, 'Liberia', ' Liberia', 'LBR'],
            [130, 'Libia', ' Libya', 'LBY'],
            [131, 'Liechtenstein', ' Liechtenstein', 'LIE'],
            [132, 'Lituania', ' Lithuania', 'LTU'],
            [133, 'Lussemburgo', ' Luxembourg', 'LUX'],
            [134, 'Macao', ' Macao', 'MAC'],
            [136, 'Madagascar', ' Madagascar', 'MDG'],
            [137, 'Malawi', ' Malawi', 'MWI'],
            [138, 'Malaysia', ' Malaysia', 'MYS'],
            [139, 'Maldive', ' Maldives', 'MDV'],
            [140, 'Mali', ' Mali', 'MLI'],
            [141, 'Malta', ' Malta', 'MLT'],
            [143, 'Martinica', ' Martinique', 'MTQ'],
            [144, 'Mauritania', ' Mauritania', 'MRT'],
            [145, 'Mauritius', ' Mauritius', 'MUS'],
            [147, 'Messico', ' Mexico', 'MEX'],
            [177, 'Monaco', ' Monaco', 'MCO'],
            [150, 'Mongolia', ' Mongolia', 'MNG'],
            [149, 'Moldavia', ' Moldova, Republic of', 'MDA'],
            [151, 'Montenegro', ' Montenegro', 'MNE'],
            [152, 'Montserrat', ' Montserrat', 'MSR'],
            [142, 'Marocco', ' Morocco', 'MAR'],
            [153, 'Mozambico', ' Mozambique', 'MOZ'],
            [164, 'Oman', ' Oman', 'OMN'],
            [154, 'Namibia', ' Namibia', 'NAM'],
            [155, 'Nauru', ' Nauru', 'NRU'],
            [156, 'Nepal', ' Nepal', 'NPL'],
            [165, 'Paesi Bassi', ' Netherlands', 'NLD'],
            [52, 'Curaçao', ' Curaçao', 'CUW'],
            [12, 'Aruba', ' Aruba', 'ABW'],
            [206, 'Sint Maarten', ' Sint Maarten', 'SXM'],
            [103, 'Isole BES', ' Bonaire, Sint Eustatius and Saba', 'BES'],
            [162, 'Nuova Caledonia', ' New Caledonia', 'NCL'],
            [243, 'Vanuatu', ' Vanuatu', 'VUT'],
            [163, 'Nuova Zelanda', ' New Zealand', 'NZL'],
            [157, 'Nicaragua', ' Nicaragua', 'NIC'],
            [158, 'Niger', ' Niger', 'NER'],
            [159, 'Nigeria', ' Nigeria', 'NGA'],
            [160, 'Niue', ' Niue', 'NIU'],
            [101, 'Isola Norfolk', ' Norfolk Island', 'NFK'],
            [161, 'Norvegia', ' Norway', 'NOR'],
            [110, 'Isole Marianne Settentrionali', ' Northern Mariana Islands', 'MNP'],
            [112, 'Isole minori esterne degli Stati Uniti', ' United States Minor Outlying Islands', 'UMI'],
            [148, 'Micronesia', ' Micronesia (Federated States of)', 'FSM'],
            [111, 'Isole Marshall', ' Marshall Islands', 'MHL'],
            [167, 'Palau', ' Palau', 'PLW'],
            [166, 'Pakistan', ' Pakistan', 'PAK'],
            [169, 'Panama', ' Panama', 'PAN'],
            [170, 'Papua Nuova Guinea', ' Papua New Guinea', 'PNG'],
            [171, 'Paraguay', ' Paraguay', 'PRY'],
            [172, 'Perù', ' Peru', 'PER'],
            [63, 'Filippine', ' Philippines', 'PHL'],
            [113, 'Isole Pitcairn', ' Pitcairn', 'PCN'],
            [174, 'Polonia', ' Poland', 'POL'],
            [176, 'Portogallo', ' Portugal', 'PRT'],
            [85, 'Guinea-Bissau', ' Guinea-Bissau', 'GNB'],
            [228, 'Timor Est', ' Timor-Leste', 'TLS'],
            [175, 'Porto Rico', ' Puerto Rico', 'PRI'],
            [178, 'Qatar', ' Qatar', 'QAT'],
            [185, 'Riunione', ' Réunion', 'REU'],
            [186, 'Romania', ' Romania', 'ROU'],
            [188, 'Russia', ' Russian Federation', 'RUS'],
            [187, 'Ruanda', ' Rwanda', 'RWA'],
            [194, 'Saint-Barthélemy', ' Saint Barthélemy', 'BLM'],
            [192, 'Sant\'Elena, Ascensione e Tristan da Cunha', ' Saint Helena, Ascension and Tristan da Cunha', 'SHN'],
            [190, 'Saint Kitts e Nevis', ' Saint Kitts and Nevis', 'KNA'],
            [6, 'Anguilla', ' Anguilla', 'AIA'],
            [191, 'Saint Lucia', ' Saint Lucia', 'LCA'],
            [195, 'Saint-Martin', ' Saint Martin', 'MAF'],
            [196, 'Saint-Pierre e Miquelon', ' Saint Pierre and Miquelon', 'SPM'],
            [193, 'Saint Vincent e Grenadine', ' Saint Vincent and the Grenadines', 'VCT'],
            [199, 'San Marino', ' San Marino', 'SMR'],
            [200, 'São Tomé e Príncipe', ' Sao Tome and Principe', 'STP'],
            [9, 'Arabia Saudita', ' Saudi Arabia', 'SAU'],
            [201, 'Senegal', ' Senegal', 'SEN'],
            [202, 'Serbia', ' Serbia', 'SRB'],
            [203, 'Seychelles', ' Seychelles', 'SYC'],
            [204, 'Sierra Leone', ' Sierra Leone', 'SLE'],
            [205, 'Singapore', ' Singapore', 'SGP'],
            [208, 'Slovacchia', ' Slovakia', 'SVK'],
            [245, 'Vietnam', ' Viet Nam', 'VNM'],
            [209, 'Slovenia', ' Slovenia', 'SVN'],
            [210, 'Somalia', ' Somalia', 'SOM'],
            [214, 'Sudafrica', ' South Africa', 'ZAF'],
            [249, 'Zimbabwe', ' Zimbabwe', 'ZWE'],
            [211, 'Spagna', ' Spain', 'ESP'],
            [216, 'Sudan del Sud', ' South Sudan', 'SSD'],
            [215, 'Sudan', ' Sudan', 'SDN'],
            [189, 'Sahara Occidentale', ' Western Sahara', 'ESH'],
            [217, 'Suriname', ' Suriname', 'SUR'],
            [218, 'Svalbard e Jan Mayen', ' Svalbard and Jan Mayen', 'SJM'],
            [221, 'eSwatini', ' Eswatini', 'SWZ'],
            [219, 'Svezia', ' Sweden', 'SWE'],
            [220, 'Svizzera', ' Switzerland', 'CHE'],
            [207, 'Siria', ' Syrian Arab Republic', 'SYR'],
            [223, 'Tagikistan', ' Tajikistan', 'TJK'],
            [227, 'Thailandia', ' Thailand', 'THA'],
            [229, 'Togo', ' Togo', 'TGO'],
            [230, 'Tokelau', ' Tokelau', 'TKL'],
            [231, 'Tonga', ' Tonga', 'TON'],
            [232, 'Trinidad e Tobago', ' Trinidad and Tobago', 'TTO'],
            [58, 'Emirati Arabi Uniti', ' United Arab Emirates', 'ARE'],
            [233, 'Tunisia', ' Tunisia', 'TUN'],
            [234, 'Turchia', ' Turkey', 'TUR'],
            [235, 'Turkmenistan', ' Turkmenistan', 'TKM'],
            [236, 'Turks e Caicos', ' Turks and Caicos Islands', 'TCA'],
            [237, 'Tuvalu', ' Tuvalu', 'TUV'],
            [239, 'Uganda', ' Uganda', 'UGA'],
            [238, 'Ucraina', ' Ukraine', 'UKR'],
            [135, 'Macedonia del Nord', ' North Macedonia', 'MKD'],
            [56, 'Egitto', ' Egypt', 'EGY'],
            [179, 'Regno Unito', ' United Kingdom of Great Britain and Northern Ireland', 'GBR'],
            [83, 'Guernsey', ' Guernsey', 'GGY'],
            [119, 'Jersey', ' Jersey', 'JEY'],
            [99, 'Isola di Man', ' Isle of Man', 'IMN'],
            [224, 'Tanzania', ' Tanzania, United Republic of', 'TZA'],
            [213, 'Stati Uniti', ' United States of America', 'USA'],
            [116, 'Isole Vergini americane', ' Virgin Islands (U.S.)', 'VIR'],
            [33, 'Burkina Faso', ' Burkina Faso', 'BFA'],
            [241, 'Uruguay', ' Uruguay', 'URY'],
            [242, 'Uzbekistan', ' Uzbekistan', 'UZB'],
            [244, 'Venezuela', ' Venezuela', 'VEN'],
            [246, 'Wallis e Futuna', ' Wallis and Futuna', 'WLF'],
            [197, 'Samoa', ' Samoa', 'WSM'],
            [247, 'Yemen', ' Yemen', 'YEM'],
            [248, 'Zambia', ' Zambia', 'ZMB'],
        ]);
    }

    public function drop() {
        $this->dropTable('places_nazioni_iso3166');
    }

}
