<?php

namespace mauriziocingolani\places\migrations;

class NazioneIT extends \mauriziocingolani\yii2fmwkphp\Migration {

    public function create() {
        $this->createTable('places_nazioni', [
            'NazioneID' => self::Pk(),
            'Nome' => self::typeVarchar(255, true),
            self::Pk('NazioneID'),
                ], self::TableOptionsLatin());
        $this->createIndex('unique_placesnazioni_nome', 'places_nazioni', 'Nome', true);
    }

    public function data() {
        $this->batchInsert('places_nazioni', ['Nome'], [
            ['Afghanistan'],
            ['Albania'],
            ['Algeria'],
            ['Samoa Americane'],
            ['Andorra'],
            ['Angola'],
            ['Anguilla'],
            ['Antartide'],
            ['Antigua e Barbuda'],
            ['Argentina'],
            ['Armenia'],
            ['Aruba'],
            ['Australia'],
            ['Austria'],
            ['Azerbaijan'],
            ['Bahamas'],
            ['Bahrain'],
            ['Bangladesh'],
            ['Barbados'],
            ['Bielorussia'],
            ['Belgio'],
            ['Belize'],
            ['Benin'],
            ['Bermuda'],
            ['Bhutan'],
            ['Bolivia'],
            ['Bosnia ed Erzegovina'],
            ['Botswana'],
            ['Isola Bouvet'],
            ['Brasile'],
            ['Territorio Britannico dell\'Oceano Indiano'],
            ['Stato del Brunei'],
            ['Bulgaria'],
            ['Burkina Faso'],
            ['Burundi'],
            ['C.A.R.'],
            ['Cambogia'],
            ['Camerun'],
            ['Canada'],
            ['Capo Verde'],
            ['Isole Cayman'],
            ['Repubblica Centrafricana'],
            ['Ciad'],
            ['Cile'],
            ['Cina'],
            ['Isola del Natale'],
            ['Isole Cocos (Keeling)'],
            ['Colombia'],
            ['Comore'],
            ['Congo'],
            ['Isola Cook'],
            ['Costa Rica'],
            ['Costa d\'Avorio'],
            ['Croazia'],
            ['Cuba'],
            ['Cipro'],
            ['Repubblica Ceca'],
            ['Danimarca'],
            ['Gibuti'],
            ['Dominica'],
            ['Repubblica Dominicana'],
            ['Timor Est'],
            ['Ecuador'],
            ['Egitto'],
            ['El Salvador'],
            ['Inghilterra'],
            ['Guinea Equatoriale'],
            ['Eritrea'],
            ['Estonia'],
            ['Etiopia'],
            ['Isole Falkland (Malvinas)'],
            ['Faroe'],
            ['Fiji'],
            ['Finlandia'],
            ['Francia'],
            ['Guyana Francese'],
            ['Polinesia Francese'],
            ['Terre Australi e Antartiche Francesi'],
            ['Gabon'],
            ['Gambia'],
            ['Georgia'],
            ['Germania'],
            ['Ghana'],
            ['Gibilterra'],
            ['Grecia'],
            ['Groenlandia'],
            ['Grenada'],
            ['Guadalupe'],
            ['Guam'],
            ['Guatemala'],
            ['Guinea'],
            ['Guinea-Bissau'],
            ['Guyana'],
            ['Haiti'],
            ['Isole Heard e Mc Donald'],
            ['Honduras'],
            ['Hong Kong'],
            ['Ungheria'],
            ['Islanda'],
            ['India'],
            ['Indonesia'],
            ['Iran'],
            ['Iraq'],
            ['Irlanda'],
            ['Israele'],
            ['Italia'],
            ['Giamaica'],
            ['Giappone'],
            ['Giordania'],
            ['Kazakistan'],
            ['Kenya'],
            ['Kiribati'],
            ['Corea del Nord'],
            ['Corea del Sud'],
            ['Kuwait'],
            ['Kirghizistan'],
            ['Laos'],
            ['Lettonia'],
            ['Libano'],
            ['Lesotho'],
            ['Liberia'],
            ['Libia'],
            ['Liechtenstein'],
            ['Lituania'],
            ['Lussenburgo'],
            ['Macao'],
            ['Macedonia'],
            ['Madagascar'],
            ['Malawi'],
            ['Malesia'],
            ['Maldive'],
            ['Mali'],
            ['Malta'],
            ['Isole Marshall'],
            ['Martinica'],
            ['Mauritania'],
            ['Mauritius'],
            ['Mayotte'],
            ['Messico'],
            ['Micronesia (Stati Federati della)'],
            ['Moldavia'],
            ['Monaco'],
            ['Mongolia'],
            ['Montserrat'],
            ['Marocco'],
            ['Mozambico'],
            ['Birmania'],
            ['Namibia'],
            ['Nauru'],
            ['Nepal'],
            ['Olanda'],
            ['Antille Olandesi'],
            ['Nuova Caledonia'],
            ['Nuova Zelanda'],
            ['Nicaragua'],
            ['Niger'],
            ['Nigeria'],
            ['Niue'],
            ['Isola Norfolk'],
            ['Irlanda del Nord'],
            ['Isole Marianne Settentrionali'],
            ['Norvegia'],
            ['Oman'],
            ['Pakistan'],
            ['Palau'],
            ['Panama'],
            ['Papua Nuova Guinea'],
            ['Paraguay'],
            ['Peru'],
            ['Filippine'],
            ['Pitcairn'],
            ['Polonia'],
            ['Portogallo'],
            ['Porto Rico'],
            ['Qatar'],
            ['Reunion'],
            ['Romania'],
            ['Russia'],
            ['Ruanda'],
            ['Saint Kitts e Nevis'],
            ['Santa Lucia'],
            ['Saint Vincent e Grenadine'],
            ['Samoa'],
            ['San Marino'],
            ['São Tomé e Príncipe'],
            ['Arabia Saudita'],
            ['Senegal'],
            ['Seychelles'],
            ['Sierra Leone'],
            ['Singapore'],
            ['Slovacchia'],
            ['Slovenia'],
            ['Isole Salomone'],
            ['Somalia'],
            ['Sudafrica'],
            ['Georgia del Sud e Isole Sandwich Meridionali'],
            ['Spagna'],
            ['Sri Lanka'],
            ['St. Helena'],
            ['St. Pierre e Miquelon'],
            ['Sudan'],
            ['Suriname'],
            ['Svalbard e Jan Mayen'],
            ['Swaziland'],
            ['Svezia'],
            ['Svizzera'],
            ['Siria'],
            ['Tahiti'],
            ['Taiwan'],
            ['Tagikistan'],
            ['Tanzania'],
            ['Tailandia'],
            ['Togo'],
            ['Tokelau'],
            ['Tonga'],
            ['Trinidad e Tobago'],
            ['Tunisia'],
            ['Turchia'],
            ['Turkmenistan'],
            ['Isole Turks e Caicos'],
            ['Tuvalu'],
            ['Uganda'],
            ['Ucraina'],
            ['Emirati Arabi Uniti'],
            ['Regno Unito'],
            ['Isole minori esterne degli Stati Uniti d\'America'],
            ['Stati Uniti'],
            ['Uruguay'],
            ['Uzbekistan'],
            ['Vanuatu'],
            ['Città del Vaticano'],
            ['Venezuela'],
            ['Vietnam'],
            ['Isole Vergini Inglesi'],
            ['Isole Vergini Americane'],
            ['Isole Wallis e Futuna'],
            ['Sahara Occidentale'],
            ['Yemen'],
            ['Yugoslavia'],
            ['Zaire'],
            ['Zambia'],
            ['Zimbabwe'],
        ]);
    }

    public function drop() {
        $this->dropTable('places_nazioni');
    }

}
